### ISSUE TITLE
Cannot find module 'electron-winstaller'

### ISSUE THREAD

**Issue by msk286** [srinivastamada/ionic-desktop#1]
When running "npm run windows-build" I have an error.
`Error: Cannot find module 'electron-winstaller'`
thanks

**Comment by bcjat** [comment]
To fix, first run
`npm install --save-dev electron-winstaller`
then
`npm run windows-build`

**Comment by ersaurabh101** [comment]
on running `npm run windows-build` i am getting this error -

```
Error: Cannot find module 'D:\ionic4\QuickTask2.0\src\windows-build.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! QuickTask2.0@0.0.1 windows-build: `node src/windows-build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the QuickTask2.0@0.0.1 windows-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by anikinitek** [comment]
while doing  npm run windows-build .  i am getting below error

Failed with exit code: 1
Output:
Fatal error: Unable to set icon

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! LoyaltyApp@0.0.1 windows-build: `node src/windows-build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the LoyaltyApp@0.0.1 windows-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Anikini\AppData\Roaming\npm-cache\_logs\2020-01-30T04_13_47_821Z-debug.log

**Comment by complabs28** [comment]
Try following all the steps listed in:
https://stackoverflow.com/questions/42308879/how-to-solve-npm-error-npm-err-code-elifecycle
